### ISSUE TITLE
Al terminar de configurar la práctica no se redirecciona

### ISSUE THREAD

**Issue by Lirlisa** [LogiLinkP/LogiLinkP.github.io#100]
**Describe the bug**
Al terminar de configurar una práctica y presionar terminar, no lleva a ningún sitio y se puede seguir apretando el botón lo que crea nuevas prácticas idénticas

**To Reproduce**
1. Crear práctica
2. Llegar al final de la configuración
3. Apretar botón Terminar

**Expected behavior**
Debería redirigir para que el encargado vea la práctica o similar

**Comment by rtallarr** [comment]
Merge hecho
