### ISSUE TITLE
Las collapsable cards de vista alumno se esconden o activan todas a la vez

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#120]

**Comment by rtallarr** [comment]
lo arreglo altoque

**Comment by Joacodef** [comment]
Hay un problema todavía. Las cartas que son de prácticas que se han terminado o están en curso, todavía se colapsan o se abren a la vez.

Esto no pasa con las cartas de prácticas que aún no se hayan cursado.
