### ISSUE TITLE
Problemas tabla de documentos en vista de detalle de prácticas

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#122]
La tabla tiene los siguientes problemas:
- [ ] Se listan los documentos subidos por el alumno; se deberían mostrar todas las solicitudes que ha hecho el encargado y que le diga cuales ya han sido respondidas y cuales no (en las respondidas se puede descargar el documento).
- [ ] En los documentos extra no se diferencia entre cuáles se han subido y cuáles no, en todos se muestra "descargar".

**Comment by rtallarr** [comment]
Merge hecho
