### ISSUE TITLE
Tabla doble

### ISSUE THREAD

**Issue by rtallarr** [LogiLinkP/LogiLinkP.github.io#24]
La tabla resumen del encargado muestra los datos y debajo dice "Ningún dato disponible en esta tabla"

**Comment by rtallarr** [comment]
arreglado

**Comment by Lirlisa** [comment]
![Image](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/42386589/fd1d21e5-1842-455f-8407-5dfa300d4226)

Nones, mestoy al día y aún aparece

**Comment by Lirlisa** [comment]
Estaba relacionado con #20 lo que ocurría es que no se recargaba datatables al recibir la data
