### ISSUE TITLE
[HDU 34] Agregar tabla publicación al backend

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#307]
- [x] Agregar y ajustar migración de creación de tabla publicación
- [x] Agregar y ajustar modelo de tabla publicación
- [x] Agregar rutas de requests:
- - [ ] GET por id_carrera para estudiantes
- - [ ] GET por id_encargado para encargados
- - [ ] POST
- - [ ] PUT
- - [ ] DELETE

**Comment by rtallarr** [comment]
pareciera estar listo(?)
