### ISSUE TITLE
[HDU 34] Agregar vista de publicaciones

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#308]
- [x] Agregar vista de publicaciones en la barra lateral (Para estudiantes y encargados)
- [x] Las publicaciones deben mostrarse en orden de fecha y de publicaciones fijas
- [x] Las publicaciones fijas deben tener mostrarse distintas para distinguirlas
- [x] Los encargados pueden agregar publicaciones
- [x] Los encargados pueden editar publicaciones
- [x] los encargados pueden borrar publicaciones
- [x] Las publicaciones con fecha de publicación deben verse sólo cuando la fecha lo indique

**Comment by rtallarr** [comment]
desarrollo terminado
