### ISSUE TITLE
[HDU 33] Crear vista documentación

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#310]
- [x] Los estudiantes pueden ver los documentos.
- [x] Los estudiantes pueden descargar los documentos.
- [x] Los encargados pueden subir y eliminar documentos.
- [x] Los documentos sólo se admiten en .pdf, .doc y .xcs
- [x] Los documentos tienen un peso límite de 10MB

**Comment by rtallarr** [comment]
desarrollo terminado
