### ISSUE TITLE
[HDU 14.1-2] Agregar seccion de informe final en alumno y encargado

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#331]
- [x] El informe final ya no sale en la tabla de los informes de avance, tiene su propia sección en detalle_practica
- [x] En vista alumno, se sigue viendo en la tabla de informes, pero sale resaltado y tiene opciones distintas
- [x] El encargado y el alumno pueden descargar la plantilla si es que existe
- [x] El encargado puede además cambiar la plantilla (eliminar, subir una nueva) en config_practica
- [x] El alumno puede subir su informe final
- [x] El encargado puede ver el informe final subido por el alumno
- [x] El alumno puede cambiar su informe final

**Comment by rtallarr** [comment]
@Joacodef terminó el desarrollo hace milenios
