### ISSUE TITLE
[HDU 17.1] Cuando alumno se registra, se le envía un correo de confirmación (no puede loguearse si no confirma)

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#343]
- [x] Se crea nueva columna activado en tabla usuario
- [x] Se crea nueva vista de confirmación
- [x] Al registrarse, se busca si existe el correo y el si usuario está activado, si no existe se crea usuario, pero inicialmente desactivado
- [x] Se envía correo con link que tiene el id_usuario encriptado
- [x] El link lleva a la nueva vista, que en seguida busca el id_usuario en bd, y pone su campo como activado=true

**Comment by rtallarr** [comment]
@Joacodef terminó el desarrollo hace milenios

**Comment by rtallarr** [comment]
@Joacodef terminó el desarrollo hace milenios
