### ISSUE TITLE
Eliminar elementos de ia

### ISSUE THREAD

**Issue by Lirlisa** [LogiLinkP/LogiLinkP.github.io#386]
Por ahora no necesitamos cosas como similitudes, detección de plagio. Resumen se trata aparte

Recordar que también se deben comentar los procesos que gatillan la ia

**Comment by rtallarr** [comment]
[Issue](https://github.com/LogiLinkP/praxus-node-backend/issues/157) en el back

**Comment by hcaballero56** [comment]
Falta arreglar eliminar el análisis de ia de las reseñas y que cuando el supervisor evalúe la práctica al terminarla pase por el python


![Image](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/42386589/389625e6-67e4-4f9b-beae-ca8164783c52)
