### ISSUE TITLE
Email enviado con direccion erronea

### ISSUE THREAD

**Issue by rtallarr** [LogiLinkP/LogiLinkP.github.io#397]
**Describe the bug**
Se manda un mail a logilink.hopto enves de la direccion que se esté usando

**To Reproduce**
1. registrar una nueva cuenta
2. revisar email recibido

**Screenshots**
al usar localhost
![image](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/89488066/3ddc61e3-6c4e-4fe6-8507-a38085ad9dc3)

**Additional context**

**Comment by Joacodef** [comment]
Eso puede ser un problema de tu .env en el backend, esta parte del código es la que define el contenido del correo, si no me equivoco (linea 292 del index.ts de usuario):

![Captura de pantalla 2024-05-22 163042](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/84486863/8875697a-90d5-4508-8220-cd2d09db99dd)

**Comment by Joacodef** [comment]
Sospecho que no es un bug, porque esa es la única parte del código donde está el texto "usuario/confirmacion?token". Revisa si está bien tu .env para cerrar el issue.
