### ISSUE TITLE
Problema en botones de aprobar y reprobar práctica en vista de resumen

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#42]
Los botones "aprobar" y "reprobar" no actualizan el estado. Causa probable: no envían la request adecuada para el backend. 
Revisar que sea de la forma:
PUT http://localhost:3000/practica/aprobar
con contenido "id_config_practica", "id_estudiante" y "aprobacion".

También cabe notar que al enviar la request correcta desde thunderclient, no se obtiene respuesta (por lo menos tras esperar 20 segundo aprox)

**Comment by rtallarr** [comment]
me funciona correctamente de forma local

**Comment by Joacodef** [comment]
el problema era que la página se recargaba antes de recibir la respuesta de la request, lo arreglé haciendo que el reload de la página estuviera dentro del complete, en donde se hace la request desde el front
