### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by rtallarr** [LogiLinkP/LogiLinkP.github.io#5]
**Describe the bug**
Al recargar la pagina se cae

**To Reproduce**
1. Go to logilinkp.github.io
2. F5 o recargar
3. See error

**Additional context**
ir directamente a https://logilinkp.github.io/home tampoco funciona

**Comment by rtallarr** [comment]
esto sigue vigente, probar ir a logilinkp.github.io/home

**Comment by Lirlisa** [comment]
Ya no aplica
