### ISSUE TITLE
Request login

### ISSUE THREAD

**Issue by rtallarr** [LogiLinkP/LogiLinkP.github.io#67]
**Describe the bug**
Al mandar request de login demora milenios y queda en time-out o CORS error.

**To Reproduce**
1. Go to login page
2. Usar cuenta valida

**Expected behavior**
Loggearse segun el usuario

**Aditional Context**
Al usar cuentas con error, por ejemplo, clave incorrecta, si manda la request y la response es la esperada

**Comment by Lirlisa** [comment]
El error era provocado por un .env desactualizado, lo probé y funciona @rtallarr
