### ISSUE TITLE
Las tarjetas collapsable de la plantilla se colapsan todas a la vez

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#75]
**Describe the bug**
Al querer desplegar o esconder una de las tarjetas en vista alumno y vista de detalles de practica, se despliegan o esconden todas las tarjetas de la vista la mismo tiempo.

**To Reproduce**
1. Ir a vista alumno o detalle_practica
2. Apretar la flecha en la esquina superior derecha de alguna tarjeta

**Additional context**
Las tarjetas collapsable se usan en vista alumno y vista detalle (por ahora). La idea es no sobrecargar de información estas páginas, por lo que son importantes desde el punto de vista de la interfaz.

**Comment by rtallarr** [comment]
Creo que esto lo puedo solucionar

**Comment by rtallarr** [comment]
solucionado en rama config_practica
