### ISSUE TITLE
Error de pop ups en vista alumno

### ISSUE THREAD

**Issue by marcelo863** [LogiLinkP/LogiLinkP.github.io#76]
En la vista alumno del frontend, cada que se quiere inscribir una práctica, sale un pop up diciendo "Error, ya tiene una práctica en curso." que no se puede cerrar. Además de esto, al insistir en inscribir una práctica, salen más pop ups que tampoco se cierran, apilándose las unas con las otras en la vista.

**Comment by Joacodef** [comment]
el error es porque echaron a perder todo cuando llegaron y eliminaron las config_practica. El alumno sí tenía una práctica en curso, pero como no tenía su config práctica asociada, no se mostraba en la vista alumno. El stackeo debe ser porque apretaste el boton muchas veces, y el tiempo de vida del snackbar quizás debe acortarse.
