### ISSUE TITLE
Doble barra de scroll

### ISSUE THREAD

**Issue by Joacodef** [LogiLinkP/LogiLinkP.github.io#84]
**Describe the bug**
Aparece una segunda barra de scroll al costado de la venta, en general al achicar la pantalla. La barra interna está bien (esa sale porque puse que los divs de clase "container-fluid" tuvieran overflow-auto). La barra externa no sé bien cómo arreglarla.

**Screenshots**
![problema barra scroll](https://github.com/LogiLinkP/LogiLinkP.github.io/assets/84486863/c28e8b24-e48b-41d2-b560-17e1d0df6915)

**Comment by rtallarr** [comment]
la pagina ya tiene un overflow setteado, no es necesaria la barra interna

**Comment by Joacodef** [comment]
Esa barra interna de scroll soluciona el problema de no tener la barra lateral fija en la pantalla, la idea es que cuando el contenido de la página exceda el tamaño de la pantalla, la barra de scroll sólo exista en el bloque de "container-fluid", que es el contenido que no incluye la barra lateral ni la superior. Así al scrollear no "mueves" la barra lateral ni superior.

Lo otro, es que había puesto que el container-fluid y la barra superior juntas tuvieran un tamaño de 100 vh, para que no apareciera otra barra de scroll, pero seguramente hay otro componente que no sigue esa regla y provoca otro overflow.

**Comment by rtallarr** [comment]
la barra externa **tiene** que existir, cuando la barra lateral tiene muchas opciones, no van a caber en el 100 vh.
> Así al scrollear no "mueves" la barra lateral ni superior.
La barra lateral se tiene que poder "mover" para poder ver opciones que quedan abajo

**Comment by Joacodef** [comment]
wn cuantas opciones quieres poner en la barra lateral que va a haber que scrollearla para verlas xD 

no debería haber que scrollear para ver todas las opciones, si es así, está mal diseñada la barra lateral

**Comment by rtallarr** [comment]
depende de cuantas practicas cree el encargado ajjaja
