### ISSUE TITLE
La opción "configurar práctica" de la barra lateral no funciona en ciertas vistas

### ISSUE THREAD

**Issue by Lirlisa** [LogiLinkP/LogiLinkP.github.io#94]
**Describe the bug**
Al apretar el botón configurar práctica desde la vista de resumen práctica y detalle práctica estando logeado como encargado no depliega el menú

**To Reproduce**

1. iniciar sesión como encargado
2. apretar botón "configurar práctica" en barra lateral

**Expected behavior**
Debería desplegarse un menú para crear una práctica nueva

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox y Chrome

**Smartphone (please complete the following information):**

**Additional context**
Se debe probar **iniciando sesión como encargado**, al logear como estudiante o entrando sin iniciar sesión si funciona

**Comment by Lirlisa** [comment]
#91

**Comment by rtallarr** [comment]
esto parece que esta bien o no?
